// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4NHP7bOIXh_QvS84JZRwtqBIde_A_WsI',
    appId: '1:686865131708:web:f121c754016723d44848b9',
    messagingSenderId: '686865131708',
    projectId: 'waiby-89732',
    authDomain: 'waiby-89732.firebaseapp.com',
    databaseURL: 'https://waiby-89732-default-rtdb.firebaseio.com',
    storageBucket: 'waiby-89732.firebasestorage.app',
    measurementId: 'G-V195160D2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA73uqaCR_yD_pzMP04FjAaJm1WCK4H89k',
    appId: '1:686865131708:android:14187e1eb86903614848b9',
    messagingSenderId: '686865131708',
    projectId: 'waiby-89732',
    databaseURL: 'https://waiby-89732-default-rtdb.firebaseio.com',
    storageBucket: 'waiby-89732.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY5jM4n-PUulpedBoMC7Q4qJlFAtq0mzk',
    appId: '1:686865131708:ios:8d23694559efd3754848b9',
    messagingSenderId: '686865131708',
    projectId: 'waiby-89732',
    databaseURL: 'https://waiby-89732-default-rtdb.firebaseio.com',
    storageBucket: 'waiby-89732.firebasestorage.app',
    iosClientId: '686865131708-d59q0kirn2ss47d38e4ofqk2m7sb3jd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY5jM4n-PUulpedBoMC7Q4qJlFAtq0mzk',
    appId: '1:686865131708:ios:8d23694559efd3754848b9',
    messagingSenderId: '686865131708',
    projectId: 'waiby-89732',
    databaseURL: 'https://waiby-89732-default-rtdb.firebaseio.com',
    storageBucket: 'waiby-89732.firebasestorage.app',
    iosClientId: '686865131708-d59q0kirn2ss47d38e4ofqk2m7sb3jd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4NHP7bOIXh_QvS84JZRwtqBIde_A_WsI',
    appId: '1:686865131708:web:467c8fa9638e4ea34848b9',
    messagingSenderId: '686865131708',
    projectId: 'waiby-89732',
    authDomain: 'waiby-89732.firebaseapp.com',
    databaseURL: 'https://waiby-89732-default-rtdb.firebaseio.com',
    storageBucket: 'waiby-89732.firebasestorage.app',
    measurementId: 'G-0W636N58LV',
  );
}
